apiVersion: apps/v1
kind: Deployment
metadata:
  name: birthday-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: birthday
  template:
    metadata:
      labels:
        app: birthday
    spec:
      containers:
        - name: birthday
          image: registry.digitalocean.com/birthday-registry/birthday-app:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 2
            periodSeconds: 5

